apiVersion: v1
kind: Service
metadata:
  name: {{ include "uxmesh.fullname" . }}-server
  labels:
{{ include "uxmesh.labels" . | indent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "uxmesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
